# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: github-action-string-transformer
  description: Github Action to transform strings based on an operation
  homepage: https://cloudposse.com/accelerate
  topics: ""
